/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFruit: typeof import('./src/components/addFruit.vue')['default']
    AllOrders: typeof import('./src/components/allOrders.vue')['default']
    BecomeVip: typeof import('./src/components/becomeVip.vue')['default']
    ClientOrder: typeof import('./src/components/clientOrder.vue')['default']
    DetailData: typeof import('./src/components/detailData.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Exit: typeof import('./src/components/exit.vue')['default']
    FadFruit: typeof import('./src/components/fadFruit.vue')['default']
    FruitCar: typeof import('./src/components/fruitCar.vue')['default']
    FruitData: typeof import('./src/components/fruitData.vue')['default']
    FruitNav: typeof import('./src/components/FruitNav.vue')['default']
    FruitOrder: typeof import('./src/components/fruitOrder.vue')['default']
    FruitShelf: typeof import('./src/components/fruitShelf.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    IncreaseInventory: typeof import('./src/components/increaseInventory.vue')['default']
    IsVip: typeof import('./src/components/isVip.vue')['default']
    Log: typeof import('./src/components/log.vue')['default']
    Logout: typeof import('./src/components/logout.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    NotVip: typeof import('./src/components/notVip.vue')['default']
    OpenAMembership: typeof import('./src/components/openAMembership.vue')['default']
    OperaFruit: typeof import('./src/components/operaFruit.vue')['default']
    OperaOrder: typeof import('./src/components/operaOrder.vue')['default']
    Order: typeof import('./src/components/order.vue')['default']
    PayOrders: typeof import('./src/components/payOrders.vue')['default']
    PayOrderSuccess: typeof import('./src/components/payOrderSuccess.vue')['default']
    PersonalSetting: typeof import('./src/components/personalSetting.vue')['default']
    PersonData: typeof import('./src/components/personData.vue')['default']
    ReCharge: typeof import('./src/components/reCharge.vue')['default']
    Reg: typeof import('./src/components/reg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table.vue')['default']
    TableList: typeof import('./src/components/tableList.vue')['default']
    Tips: typeof import('./src/components/tips.vue')['default']
    ToShopping: typeof import('./src/components/toShopping.vue')['default']
  }
}
